import { useState, useEffect, useRef } from 'react';
import DemoScenarios from '../components/DemoScenarios';
import TaskInput from '../components/TaskInput';
import AgentTrace from '../components/AgentTrace';
import { useAgentStream } from '../hooks/useAgentStream';
import { Zap, Clock, Cpu } from 'lucide-react';

export default function NewTask() {
  const { run, isLoading, result } = useAgentStream();
  const [taskData, setTaskData] = useState({ task: '', format: 'Word Doc', file: null });
  const traceRef = useRef(null);

  const handleScenario = (scenario) => {
    // Pre-fill task and immediately run
    setTaskData({ task: scenario.task, format: scenario.format, file: null });
    setTimeout(() => {
      run({ task: scenario.task, format: scenario.format, file: null, scenario: scenario.scenario });
      if (traceRef.current) {
        traceRef.current.scrollIntoView({ behavior: 'smooth' });
      }
    }, 100);
  };

  const handleSubmit = ({ task, format, file }) => {
    setTaskData({ task, format, file });
    run({ task, format, file });
    setTimeout(() => {
      if (traceRef.current) {
        traceRef.current.scrollIntoView({ behavior: 'smooth' });
      }
    }, 200);
  };

  const handleDownload = (filename) => {
    // Create a dummy download for demo purposes
    const content = filename.endsWith('.py')
      ? `# Generated by Sovereign AI Workbench\n# SIH 2026 | Team Code:201\n\nimport json\nimport numpy as np\n\ndef parse_sensor_logs(log_file, threshold_std=3.0):\n    """Parse JSON sensor logs and flag anomalies."""\n    with open(log_file) as f:\n        logs = json.load(f)\n    # ... implementation\n    return {"anomalies": []}\n`
      : `Sovereign AI Workbench — SIH 2026\nTeam Code:201 | Demo Output\n\nThis is a demo-generated file.\nIn production, this would contain the actual AI-generated content.`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-text-primary">Agentic Workbench</h1>
          <p className="text-sm text-text-muted mt-0.5">Submit tasks to the multi-model agentic pipeline</p>
        </div>
        <div className="flex items-center gap-3">
          {result && (
            <>
              <div className="flex items-center gap-1.5 text-xs text-text-muted">
                <Clock size={12} />
                <span className="font-mono">{(result.time_taken_ms / 1000).toFixed(1)}s</span>
              </div>
              <div className="flex items-center gap-1.5 text-xs text-text-muted">
                <Cpu size={12} />
                <span className="text-accent-warn font-mono">{result.model_used}</span>
              </div>
              <span className="badge-accent text-[10px]">0 bytes outbound</span>
            </>
          )}
        </div>
      </div>

      {/* Quick Launch Scenarios */}
      <DemoScenarios onSelect={handleScenario} />

      {/* Split panel */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left — Task Input */}
        <div className="card p-5">
          <h2 className="font-semibold text-text-primary mb-4 flex items-center gap-2">
            <Zap size={16} className="text-accent" />
            Task Input
          </h2>
          <TaskInput
            onSubmit={handleSubmit}
            isLoading={isLoading}
            initialTask={taskData.task}
            initialFormat={taskData.format}
          />
        </div>

        {/* Right — Agent Trace */}
        <div ref={traceRef} className="card p-5 overflow-y-auto" style={{ maxHeight: '80vh' }}>
          <AgentTrace
            steps={result?.steps}
            isRunning={isLoading}
            onDownload={handleDownload}
          />

          {/* Final response */}
          {result?.final_response && (
            <div className="mt-4 p-4 rounded-lg border"
              style={{ background: 'rgba(0,200,150,0.04)', borderColor: 'rgba(0,200,150,0.15)' }}>
              <h4 className="text-xs font-semibold text-text-muted uppercase tracking-wider mb-2">
                📋 Generated Output Preview
              </h4>
              <div className="text-xs text-text-muted font-mono whitespace-pre-wrap leading-5 max-h-48 overflow-y-auto">
                {result.final_response.slice(0, 800)}
                {result.final_response.length > 800 && '…'}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
